### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by voidrinix** [isXander/AdaptiveTooltips#11]
[crash-2022-12-29_21.24.41.7642-quilt_loader.txt](https://github.com/isXander/AdaptiveTooltips/files/10320949/crash-2022-12-29_21.24.41.7642-quilt_loader.txt)
Hello! MC 1.19.3, Quilt Loader 0.18.1 beta 25, Adaptive Tooltips 1.1.1, YACL 2.2.0

**Comment by isXander** [comment]
This seems like the incorrect log, is there one without quilt loader suffix?

**Comment by voidrinix** [comment]
> This seems like the incorrect log, is there one without quilt loader suffix?

the crash appears only on quilt 0.18.1 beta25, on quilt 0.17.8 everything is ok. I think it's quilt issue
