### ISSUE TITLE
[1.19.3] Adaptive Tooltips keeps crashing when Quilt Loader is present

### ISSUE THREAD

**Issue by stantios** [isXander/AdaptiveTooltips#12]
Quilt Loader Version: 0.18.1-beta.25
Logs: https://mclo.gs/Bw56WUI
Screenshot: 
![image](https://user-images.githubusercontent.com/98621617/210148955-c207cc8a-7bdd-476c-8a34-7d2eb825e94e.png)

Description: It keeps asking for 2.x.x for YACL but I've got latest version available for 1.19.3 so I'm not sure how to resolve this.

**Comment by jucogjucogi** [comment]
and how do i fix it?
