### ISSUE TITLE
[Feature Request] Tooltip Freezing

### ISSUE THREAD

**Issue by Julienraptor01** [isXander/AdaptiveTooltips#20]
It could be great if by pressing a key, we could "Freeze" the tooltip, like stop it from being updated even if the server send a diff version
Idk if it's actually possible whitout creating problem but if would allow for scrolling to not be reset when the tooltip change because it wouldn't be changed in the 1st place
If you want to test the problem of the tooltip being reset while scrolling :
Go on Hypixel Skyblock
Look for an item on AH with short lasting delay
Try to scroll and see that each time the tooltip update the scroll is reset

**Comment by isXander** [comment]
This is not feasible, every frame, various pieces of code call the tooltip render method, with a text component. There is no way to identify if one tooltip is the same.
