### ISSUE TITLE
BetterPvP crashes when ItemTooltip is enabled

### ISSUE THREAD

**Issue by SheerYin** [isXander/AdaptiveTooltips#25]
![image](https://user-images.githubusercontent.com/83099762/233226653-0896a336-88ba-42eb-83da-7dc671e9dd19.png)

**Comment by isXander** [comment]
log?

**Comment by SheerYin** [comment]
[crash-2023-05-02_15.45.32-client.log](https://github.com/isXander/AdaptiveTooltips/files/11370886/crash-2023-05-02_15.45.32-client.log)
[latest.log](https://github.com/isXander/AdaptiveTooltips/files/11370888/latest.log)

Doesn't crash on latest version:
AdaptiveTooltips-1.2.1-fabric-1.19.4.jar
YetAnotherConfigLib-2.5.0+1.19.4.jar
