### ISSUE TITLE
enable scrolling without pressing a key

### ISSUE THREAD

**Issue by Sombian** [isXander/AdaptiveTooltips#6]
thanks in advance.

**Comment by isXander** [comment]
Will add an option

**Comment by isXander** [comment]
This would break all guis that have mouse scrolling.

**Comment by Sombian** [comment]
> This would break all guis that have mouse scrolling.

what about toggle option then?

**Comment by Sombian** [comment]
> This would break all guis that have mouse scrolling.

understood
